// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Command struct {
	ID         int32     `json:"id"`
	Command    string    `json:"command"`
	CreateTime time.Time `json:"create_time"`
}

type RepeatDay struct {
	ID         int32     `json:"id"`
	ScheduleID int32     `json:"schedule_id"`
	Day        string    `json:"day"`
	CreateTime time.Time `json:"create_time"`
}

type RepeatMonth struct {
	ID         int32     `json:"id"`
	ScheduleID int32     `json:"schedule_id"`
	Month      string    `json:"month"`
	CreateTime time.Time `json:"create_time"`
}

type RepeatWeekday struct {
	ID         int32     `json:"id"`
	ScheduleID int32     `json:"schedule_id"`
	Weekday    string    `json:"weekday"`
	CreateTime time.Time `json:"create_time"`
}

type Schedule struct {
	ID int32 `json:"id"`
	// template type
	TimeTypeID  int32 `json:"time_type_id"`
	IntervalDay int32 `json:"interval_day"`
	// repeat in day
	IntervalSeconds int32  `json:"interval_seconds"`
	AtTime          string `json:"at_time"`
	StartTime       string `json:"start_time"`
	EndTime         string `json:"end_time"`
	CommandID       int32  `json:"command_id"`
	// template name
	Name       string    `json:"name"`
	StartDate  time.Time `json:"start_date"`
	EndDate    time.Time `json:"end_date"`
	Enable     bool      `json:"enable"`
	Repeat     bool      `json:"repeat"`
	CreateTime time.Time `json:"create_time"`
}

type ListRepeatWeekdaysRow struct {
	ScheduleID int32  `json:"schedule_id"`
	Weekday    string `json:"weekday"`
}

type ListRepeatMonthsRow struct {
	ScheduleID int32  `json:"schedule_id"`
	Month      string `json:"month"`
}

type ListRepeatDaysRow struct {
	ScheduleID int32  `json:"schedule_id"`
	Day        string `json:"day"`
}

type SubResult struct {
	RepeatWeekday []ListRepeatWeekdaysRow `json:"repeat_weekday"`
	RepeatMonth   []ListRepeatMonthsRow   `json:"repeat_month"`
	RepeatDay     []ListRepeatDaysRow     `json:"repeat_day"`
}
